repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
    - id: format
      name: format
      entry: bash -c 'invoke format'
      language: system
      types: [python]
      pass_filenames: false
    - id: lint
      name: lint
      entry: bash -c 'invoke lint'
      language: system
      types: [python]
      pass_filenames: false
    - id: security
      name: security
      entry: bash -c 'invoke security'
      language: system
      types: [python]
      pass_filenames: false
