[tool]
[tool.poetry]
authors = ["Mickey Kim <mickeykkim@gmail.com>"]
classifiers = [
  'Development Status :: 2 - Pre-Alpha',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: MIT License',
  'Natural Language :: English',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.5',
  'Programming Language :: Python :: 3.6',
  'Programming Language :: Python :: 3.7',
  'Programming Language :: Python :: 3.8',
]
description = "Top-level package for inky-pi."
homepage = "https://github.com/mickeykkim/inky_pi"
license = "MIT"
name = "inky_pi"
packages = [{include = "inky_pi"}, {include = "tests", format = "sdist"}]
readme = "README.rst"
version = "0.1.0"

[[tool.poetry.source]]
default = true
name = "pypi-public"
url = "https://pypi.org/simple/"

[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple/"

[tool.poetry.dependencies]
Pillow = "^9.0.0"
"RPi.GPIO" = {version = "^0.7.0", markers = "platform_machine == 'armv7l'"}
click = "*"
environs = "^9.3.2"
font-fredoka-one = "^0.0.4"
font-hanken-grotesk = "^0.0.2"
inky = {version = "^1.2.0", markers = "platform_machine == 'armv7l'"}
loguru = "^0.5.3"
python = ">=3.7,<4"
urllib3 = "^1.26.8"
zeep = "^4.0.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
bumpversion = "*"
coverage = "*"
flake8 = "^3.9.2"
importlib-metadata = "^1.7.0"
invoke = "*"
mypy = "^0.910"
pre-commit = "^2.17.0"
pylint = "^2.0"
pytest = "^6.2.5"
sphinx = "*"
sphinx-rtd-theme = "^1.0.0"
tox = "^3.24.4"
types-requests = "^2.25.8"

[tool.poetry.scripts]
inky_pi = 'inky_pi.cli:main'

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
