[tool]
[tool.poetry]
name = "inky_pi"
version = "0.1.0"
homepage = "https://github.com/mickeykkim/inky_pi"
description = "Top-level package for inky-pi."
authors = ["Mickey Kim <mickeykkim@gmail.com>"]
readme = "README.rst"
license =  "MIT"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
packages = [
    { include = "inky_pi" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
click = "*"
font-hanken-grotesk = "^0.0.2"
inky = "^1.2.0"
"RPi.GPIO" = "^0.7.0"
Pillow = "^9.0.0"
environs = "^9.3.2"
zeep = "^4.0.0"
font-fredoka-one = "^0.0.4"
loguru = "^0.5.3"
urllib3 = "^1.26.8"

[tool.poetry.dev-dependencies]
bumpversion = "*"
coverage = "*"
flake8 = "*"
invoke = "*"
pylint = "^2.0"
pytest = "*"
sphinx = "*"
tox = "*"
mypy = "^0.910"
types-requests = "^2.25.0"
black = "^22.1.0"

[tool.poetry.scripts]
inky_pi = 'inky_pi.cli:main'

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
